### ISSUE TITLE
undefined id not an object

### ISSUE THREAD

**Issue by lqzkl** [wangyankun33/react-native-cn-tts-demo#2]
react-native-cn-tts   undefined id not an object(evaluating '_reactNativeCnTts2.default.speak')

**Comment by wangyankun33** [comment]
> react-native-cn-tts undefined id not an object(evaluating '_reactNativeCnTts2.default.speak')

Check your  React and React-native version!Need to provide your React  and  React-native!

**Comment by lqzkl** [comment]
Thanks for your teach.
